export const TYPES={
    ADD_TO_VENTAS:"ADD_TO_VENTAS",
    REMOVE_ONE_FROM_VENTAS:"REMOVE_ONE_FROM_VENTAS",
    REMOVE_ALL_FROM_VENTAS:"REMOVE_ALL_FROM_VENTAS",
    CLEAR_VENTAS:"CLEAR_VENTAS",
    READ_ALL_DATA:"READ_ALL_DATA",
};